services:
  odoo:
    image: ghcr.io/${OWNER:-oca}/oca-custom:${IMAGE_VERSION:-14.0-oca-latest}
    build:
      context: ./
    networks:
      - internal
      - kwkhtmltopdf
    volumes:
      - oca_filestore:/data/odoo/filestore
    command: ["odoo"]
    ports:
      - 8069:8069
    environment:
      - DB_HOST=db
      - DB_PASSWORD=${POSTGRES_PASSWORD:-ocapwd}
      - DB_USER=${POSTGRES_USER:-oca}
      - DB_NAME=${POSTGRES_DB:-oca}
      - UNACCENT=True
      - WORKERS=0
      - LIST_DB=False
      - WITHOUT_DEMO=False
      - KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf:8080
      - ODOO_REPORT_URL=http://odoo:8069
      - RUNNING_ENV=dev
      - SOURCE_CODE_LOCAL_PATH=/tmp
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/0.0.0.0/8069"]
      interval: 2s
      timeout: 200ms
      retries: 150
    depends_on:
      - db
      - kwkhtmltopdf

  db:
    image: postgres:16.9
    volumes:
      - oca_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-oca}
      POSTGRES_USER: ${POSTGRES_USER:-oca}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ocapwd}
    networks:
      - internal
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER:-oca} -d ${POSTGRES_DB:-oca}'",
        ]
      interval: 3s
      timeout: 2s
      retries: 3

  kwkhtmltopdf:
    image: ghcr.io/acsone/kwkhtmltopdf:0.12.5-latest
    init: true
    networks:
      - kwkhtmltopdf

networks:
  internal:
  kwkhtmltopdf:

volumes:
  oca_pgdata:
    driver: local
  oca_filestore:
    driver: local
