from .vcp_odoo_module_version_serializer import VcpOdooModuleVersionSerializer
from .res_partner_serializer import CompanySerializer, PersonSerializer
# from .vcp_psc_team_serializer import PscSerializer
