#!/bin/bash
set -euxo pipefail

psql -c "
    DELETE FROM ir_model_data
    WHERE model='ir.model.fields'
    AND module='website_crm_partner_assign'
    AND res_id not in (select id from ir_model_fields)
    "
click-odoo-uninstall -m website_crm_partner_assign
