from . import vcp_odoo_module
from . import vcp_odoo_module_version
from . import vcp_repository
from . import vcp_repository_category
from . import vcp_rule
from . import vcp_user
from . import res_partner
from . import vcp_organization_history
from . import vcp_review
from . import vcp_comment
