#!/usr/bin/env python
import logging
import os
import sys

import click
import click_odoo
from click_odoo import odoo

_logger = logging.getLogger(__name__)


def neutralize_db(env):
    if odoo.release.version_info >= (16, 0):
        _logger.info("Neutralizing database (Odoo >= 16 detected)")
        odoo.modules.neutralize.neutralize_database(env.cr)
        env.cr.commit()
    else:
        _logger.warning(
            "Skipping neutralization: Odoo version is %s (< 16.0)",
            getattr(odoo.release, "version", odoo.release.version_info),
        )


@click.command()
@click_odoo.env_options(with_rollback=False)
def main(env):
    running_env = os.getenv("RUNNING_ENV")
    if not running_env:
        _logger.info(
            "RUNNING_ENV is not defined, please set a RUNNING_ENV and try again"
        )
        sys.exit(1)
    if running_env == "prod" or "prod" in env.registry.db_name:
        _logger.info("%s database, no need to neutralize...", running_env)
        sys.exit(0)

    neutralize_db(env)


if __name__ == "__main__":
    main()
