#!/bin/bash
set -e
set -x

if [[ -z "${RUNNING_ENV}" ]]
then
    echo "RUNNING_ENV is not defined, please set a RUNNING_ENV and try again"
    exit 1
else

    if [ "$RUNNING_ENV" != 'prod' ]
    then
        echo "Neutralizing $RUNNING_ENV database..."
    else
        echo "$RUNNING_ENV database, no needs to neutralize..."
        exit 0
    fi
fi

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database $DB_NAME does not exist, skipping $0"
    exit 0
fi

if [ "$( psql $DB_NAME -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
then
    echo "Database $DB_NAME not initialized, skipping $0"
    exit 0
fi

if [ "$( psql $DB_NAME -tAc "SELECT count(*) FROM ir_config_parameter WHERE key='database.is_neutralized' AND value='true'" )" != '0' ]
then
    echo "No OP: Database $DB_NAME already neutralized."
    exit 0
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
shopt -s nullglob
for file in "$SCRIPT_DIR"/*.sql; do
    psql  $DB_NAME -tAf "${file}"
done
