name: Build Docker Image

on:
  pull_request:
    branches:
      - "14.0*"
  push:
    branches:
      - "14.0"
    tags:
      - 'v14.0.*'

env:
  OWNER: "oca"


jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        if: ${{ github.repository_owner == env.OWNER && github.ref == 'refs/heads/14.0' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ env.OWNER }}/oca-custom:14.0-oca-latest
          cache-from: type=registry,ref=ghcr.io/oca/oca-custom:14.0-oca-latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          pull: true
          load: true
      -
        name: Test install oca_all in docker image
        run: |
          # First start installing the database
          docker compose up --wait odoo
          docker compose stop odoo
          # purpose it to test update entrypoints
          docker compose up --wait odoo
      - name: Show docker logs on failure
        if: failure()
        run: |
          echo "Build failed, showing container logs..."
          docker compose ps || true
          docker compose logs --no-color || true
      -
        name: Push latests cache image
        if: ${{ github.repository_owner == env.OWNER && github.ref == 'refs/heads/14.0' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ env.OWNER }}/oca-custom:14.0-oca-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=inline
          push: true
      -
        name: Push image with tag if tagged
        if: ${{ github.repository_owner == env.OWNER && startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ env.OWNER }}/oca-custom:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=inline
          push: true
